spring:
  application:
    name: wanted-pre-onboarding-backend
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanted
    username: wanted
    password: wanted1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080
